name: Weekly Scrape and Commit

on:
  schedule:
    - cron: '0 19 * * 6'  # Every Saturday 22:00 Israel time (UTC+3)
  workflow_dispatch:      # Allow manual trigger

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run scraper using npm script
        run: npm run scrape

      - name: Commit and push updated /data
        run: |
            git config --global user.email "actions@github.com"
            git config --global user.name "github-actions[bot]"
            git add data

            if ! git diff --cached --quiet; then
            git commit -m "📦 Weekly data update"
            git pull --rebase origin ${{ github.ref_name }}
            git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:${{ github.ref_name }}
            else
            echo "No changes to commit."
            fi


